M48
; DRILL file {KiCad (6.0.0)} date Sat Apr 26 12:20:18 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-04-26T12:20:18+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0394
%
G90
G05
T1
X5.55Y-3.65
X5.55Y-3.85
X5.85Y-3.65
X5.85Y-3.85
T2
X6.15Y-3.75
X6.25Y-3.75
X6.7Y-3.75
X6.8Y-3.75
T3
X4.95Y-3.65
X4.95Y-3.75
X4.95Y-3.85
T0
M30
